# SPDX-FileCopyrightText: 2026 Alexandru Ciobanu
# SPDX-License-Identifier: MIT

changelog:
  exclude:
    labels: [skip-changelog]
  categories:
    - title: Fixes
      labels: [bug]
    - title: Features
      labels: [enhancement]
    - title: Build and dependencies
      labels: [dependencies]
    - title: Other changes
      labels: ['*']
